// Code generated by protoc-gen-go. DO NOT EDIT.
// source: moc_hostagent_virtualmachine.proto

package compute

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/microsoft/moc/rpc/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VirtualMachine struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string         `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Entity               *common.Entity `protobuf:"bytes,3,opt,name=entity,proto3" json:"entity,omitempty"`
	Tags                 *common.Tags   `protobuf:"bytes,4,opt,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *VirtualMachine) Reset()         { *m = VirtualMachine{} }
func (m *VirtualMachine) String() string { return proto.CompactTextString(m) }
func (*VirtualMachine) ProtoMessage()    {}
func (*VirtualMachine) Descriptor() ([]byte, []int) {
	return fileDescriptor_78f422aa176e1be1, []int{0}
}

func (m *VirtualMachine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachine.Unmarshal(m, b)
}
func (m *VirtualMachine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachine.Marshal(b, m, deterministic)
}
func (m *VirtualMachine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachine.Merge(m, src)
}
func (m *VirtualMachine) XXX_Size() int {
	return xxx_messageInfo_VirtualMachine.Size(m)
}
func (m *VirtualMachine) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachine.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachine proto.InternalMessageInfo

func (m *VirtualMachine) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VirtualMachine) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VirtualMachine) GetEntity() *common.Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *VirtualMachine) GetTags() *common.Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

type RegisterVirtualMachineRequest struct {
	VirtualMachine       *VirtualMachine `protobuf:"bytes,1,opt,name=VirtualMachine,proto3" json:"VirtualMachine,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RegisterVirtualMachineRequest) Reset()         { *m = RegisterVirtualMachineRequest{} }
func (m *RegisterVirtualMachineRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterVirtualMachineRequest) ProtoMessage()    {}
func (*RegisterVirtualMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78f422aa176e1be1, []int{1}
}

func (m *RegisterVirtualMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterVirtualMachineRequest.Unmarshal(m, b)
}
func (m *RegisterVirtualMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterVirtualMachineRequest.Marshal(b, m, deterministic)
}
func (m *RegisterVirtualMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterVirtualMachineRequest.Merge(m, src)
}
func (m *RegisterVirtualMachineRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterVirtualMachineRequest.Size(m)
}
func (m *RegisterVirtualMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterVirtualMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterVirtualMachineRequest proto.InternalMessageInfo

func (m *RegisterVirtualMachineRequest) GetVirtualMachine() *VirtualMachine {
	if m != nil {
		return m.VirtualMachine
	}
	return nil
}

type RegisterVirtualMachineResponse struct {
	InstanceView         *common.RegisterVirtualMachineInstanceView `protobuf:"bytes,1,opt,name=InstanceView,proto3" json:"InstanceView,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *RegisterVirtualMachineResponse) Reset()         { *m = RegisterVirtualMachineResponse{} }
func (m *RegisterVirtualMachineResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterVirtualMachineResponse) ProtoMessage()    {}
func (*RegisterVirtualMachineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78f422aa176e1be1, []int{2}
}

func (m *RegisterVirtualMachineResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterVirtualMachineResponse.Unmarshal(m, b)
}
func (m *RegisterVirtualMachineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterVirtualMachineResponse.Marshal(b, m, deterministic)
}
func (m *RegisterVirtualMachineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterVirtualMachineResponse.Merge(m, src)
}
func (m *RegisterVirtualMachineResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterVirtualMachineResponse.Size(m)
}
func (m *RegisterVirtualMachineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterVirtualMachineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterVirtualMachineResponse proto.InternalMessageInfo

func (m *RegisterVirtualMachineResponse) GetInstanceView() *common.RegisterVirtualMachineInstanceView {
	if m != nil {
		return m.InstanceView
	}
	return nil
}

type DeregisterVirtualMachineRequest struct {
	VirtualMachine       *VirtualMachine `protobuf:"bytes,1,opt,name=VirtualMachine,proto3" json:"VirtualMachine,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DeregisterVirtualMachineRequest) Reset()         { *m = DeregisterVirtualMachineRequest{} }
func (m *DeregisterVirtualMachineRequest) String() string { return proto.CompactTextString(m) }
func (*DeregisterVirtualMachineRequest) ProtoMessage()    {}
func (*DeregisterVirtualMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78f422aa176e1be1, []int{3}
}

func (m *DeregisterVirtualMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeregisterVirtualMachineRequest.Unmarshal(m, b)
}
func (m *DeregisterVirtualMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeregisterVirtualMachineRequest.Marshal(b, m, deterministic)
}
func (m *DeregisterVirtualMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeregisterVirtualMachineRequest.Merge(m, src)
}
func (m *DeregisterVirtualMachineRequest) XXX_Size() int {
	return xxx_messageInfo_DeregisterVirtualMachineRequest.Size(m)
}
func (m *DeregisterVirtualMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeregisterVirtualMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeregisterVirtualMachineRequest proto.InternalMessageInfo

func (m *DeregisterVirtualMachineRequest) GetVirtualMachine() *VirtualMachine {
	if m != nil {
		return m.VirtualMachine
	}
	return nil
}

type DeregisterVirtualMachineResponse struct {
	InstanceView         *common.DeregisterVirtualMachineInstanceView `protobuf:"bytes,1,opt,name=InstanceView,proto3" json:"InstanceView,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *DeregisterVirtualMachineResponse) Reset()         { *m = DeregisterVirtualMachineResponse{} }
func (m *DeregisterVirtualMachineResponse) String() string { return proto.CompactTextString(m) }
func (*DeregisterVirtualMachineResponse) ProtoMessage()    {}
func (*DeregisterVirtualMachineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78f422aa176e1be1, []int{4}
}

func (m *DeregisterVirtualMachineResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeregisterVirtualMachineResponse.Unmarshal(m, b)
}
func (m *DeregisterVirtualMachineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeregisterVirtualMachineResponse.Marshal(b, m, deterministic)
}
func (m *DeregisterVirtualMachineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeregisterVirtualMachineResponse.Merge(m, src)
}
func (m *DeregisterVirtualMachineResponse) XXX_Size() int {
	return xxx_messageInfo_DeregisterVirtualMachineResponse.Size(m)
}
func (m *DeregisterVirtualMachineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeregisterVirtualMachineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeregisterVirtualMachineResponse proto.InternalMessageInfo

func (m *DeregisterVirtualMachineResponse) GetInstanceView() *common.DeregisterVirtualMachineInstanceView {
	if m != nil {
		return m.InstanceView
	}
	return nil
}

type VirtualMachineRunCommandRequest struct {
	VirtualMachine            *VirtualMachine                                  `protobuf:"bytes,1,opt,name=VirtualMachine,proto3" json:"VirtualMachine,omitempty"`
	Source                    *common.VirtualMachineRunCommandScriptSource     `protobuf:"bytes,2,opt,name=Source,proto3" json:"Source,omitempty"`
	RunCommandInputParameters []*common.VirtualMachineRunCommandInputParameter `protobuf:"bytes,3,rep,name=RunCommandInputParameters,proto3" json:"RunCommandInputParameters,omitempty"`
	RunAsUser                 string                                           `protobuf:"bytes,4,opt,name=RunAsUser,proto3" json:"RunAsUser,omitempty"`
	RunAsPassword             string                                           `protobuf:"bytes,5,opt,name=RunAsPassword,proto3" json:"RunAsPassword,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                                         `json:"-"`
	XXX_unrecognized          []byte                                           `json:"-"`
	XXX_sizecache             int32                                            `json:"-"`
}

func (m *VirtualMachineRunCommandRequest) Reset()         { *m = VirtualMachineRunCommandRequest{} }
func (m *VirtualMachineRunCommandRequest) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineRunCommandRequest) ProtoMessage()    {}
func (*VirtualMachineRunCommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78f422aa176e1be1, []int{5}
}

func (m *VirtualMachineRunCommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineRunCommandRequest.Unmarshal(m, b)
}
func (m *VirtualMachineRunCommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineRunCommandRequest.Marshal(b, m, deterministic)
}
func (m *VirtualMachineRunCommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineRunCommandRequest.Merge(m, src)
}
func (m *VirtualMachineRunCommandRequest) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineRunCommandRequest.Size(m)
}
func (m *VirtualMachineRunCommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineRunCommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineRunCommandRequest proto.InternalMessageInfo

func (m *VirtualMachineRunCommandRequest) GetVirtualMachine() *VirtualMachine {
	if m != nil {
		return m.VirtualMachine
	}
	return nil
}

func (m *VirtualMachineRunCommandRequest) GetSource() *common.VirtualMachineRunCommandScriptSource {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *VirtualMachineRunCommandRequest) GetRunCommandInputParameters() []*common.VirtualMachineRunCommandInputParameter {
	if m != nil {
		return m.RunCommandInputParameters
	}
	return nil
}

func (m *VirtualMachineRunCommandRequest) GetRunAsUser() string {
	if m != nil {
		return m.RunAsUser
	}
	return ""
}

func (m *VirtualMachineRunCommandRequest) GetRunAsPassword() string {
	if m != nil {
		return m.RunAsPassword
	}
	return ""
}

type VirtualMachineRunCommandResponse struct {
	VirtualMachine       *VirtualMachine                              `protobuf:"bytes,1,opt,name=VirtualMachine,proto3" json:"VirtualMachine,omitempty"`
	InstanceView         *common.VirtualMachineRunCommandInstanceView `protobuf:"bytes,2,opt,name=InstanceView,proto3" json:"InstanceView,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *VirtualMachineRunCommandResponse) Reset()         { *m = VirtualMachineRunCommandResponse{} }
func (m *VirtualMachineRunCommandResponse) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineRunCommandResponse) ProtoMessage()    {}
func (*VirtualMachineRunCommandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78f422aa176e1be1, []int{6}
}

func (m *VirtualMachineRunCommandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineRunCommandResponse.Unmarshal(m, b)
}
func (m *VirtualMachineRunCommandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineRunCommandResponse.Marshal(b, m, deterministic)
}
func (m *VirtualMachineRunCommandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineRunCommandResponse.Merge(m, src)
}
func (m *VirtualMachineRunCommandResponse) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineRunCommandResponse.Size(m)
}
func (m *VirtualMachineRunCommandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineRunCommandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineRunCommandResponse proto.InternalMessageInfo

func (m *VirtualMachineRunCommandResponse) GetVirtualMachine() *VirtualMachine {
	if m != nil {
		return m.VirtualMachine
	}
	return nil
}

func (m *VirtualMachineRunCommandResponse) GetInstanceView() *common.VirtualMachineRunCommandInstanceView {
	if m != nil {
		return m.InstanceView
	}
	return nil
}

func init() {
	proto.RegisterType((*VirtualMachine)(nil), "moc.hostagent.compute.VirtualMachine")
	proto.RegisterType((*RegisterVirtualMachineRequest)(nil), "moc.hostagent.compute.RegisterVirtualMachineRequest")
	proto.RegisterType((*RegisterVirtualMachineResponse)(nil), "moc.hostagent.compute.RegisterVirtualMachineResponse")
	proto.RegisterType((*DeregisterVirtualMachineRequest)(nil), "moc.hostagent.compute.DeregisterVirtualMachineRequest")
	proto.RegisterType((*DeregisterVirtualMachineResponse)(nil), "moc.hostagent.compute.DeregisterVirtualMachineResponse")
	proto.RegisterType((*VirtualMachineRunCommandRequest)(nil), "moc.hostagent.compute.VirtualMachineRunCommandRequest")
	proto.RegisterType((*VirtualMachineRunCommandResponse)(nil), "moc.hostagent.compute.VirtualMachineRunCommandResponse")
}

func init() {
	proto.RegisterFile("moc_hostagent_virtualmachine.proto", fileDescriptor_78f422aa176e1be1)
}

var fileDescriptor_78f422aa176e1be1 = []byte{
	// 530 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x93, 0x10, 0x29, 0x13, 0xe8, 0x61, 0x11, 0x60, 0x22, 0xb5, 0x8d, 0x8c, 0x10, 0x01,
	0x24, 0x07, 0x85, 0xaf, 0x73, 0x0a, 0x1c, 0x2a, 0x14, 0xa9, 0xda, 0x42, 0x0f, 0x5c, 0xaa, 0xed,
	0x66, 0x71, 0x56, 0x62, 0x77, 0xdd, 0xdd, 0x35, 0x85, 0x13, 0x47, 0xb8, 0xf0, 0x5f, 0xb8, 0x70,
	0xe7, 0x17, 0xf1, 0x1b, 0x90, 0xd7, 0x26, 0x89, 0xad, 0x6c, 0x42, 0x25, 0xe0, 0x94, 0x64, 0xe6,
	0xbd, 0x79, 0x6f, 0x26, 0x33, 0x36, 0x44, 0x42, 0xd1, 0x93, 0x99, 0x32, 0x96, 0x24, 0x4c, 0xda,
	0x93, 0xf7, 0x5c, 0xdb, 0x8c, 0xbc, 0x13, 0x84, 0xce, 0xb8, 0x64, 0x71, 0xaa, 0x95, 0x55, 0xe8,
	0x9a, 0x50, 0x34, 0x9e, 0x63, 0x62, 0xaa, 0x44, 0x9a, 0x59, 0xd6, 0xbb, 0x91, 0x53, 0xa9, 0x12,
	0x42, 0xc9, 0xf2, 0xa3, 0xc0, 0xf7, 0x76, 0xab, 0x89, 0x1c, 0xbc, 0x9c, 0x8f, 0x3e, 0xc0, 0xf6,
	0x71, 0xa1, 0x33, 0x29, 0x74, 0x10, 0x82, 0x96, 0x24, 0x82, 0x85, 0x41, 0x3f, 0x18, 0x74, 0xb0,
	0xfb, 0x8e, 0xb6, 0xa1, 0xc1, 0xa7, 0x61, 0xc3, 0x45, 0x1a, 0x7c, 0x8a, 0x6e, 0x41, 0x9b, 0x49,
	0xcb, 0xed, 0xc7, 0xb0, 0xd9, 0x0f, 0x06, 0xdd, 0x51, 0x37, 0xce, 0x6d, 0xbd, 0x70, 0x21, 0x5c,
	0xa6, 0xd0, 0x0e, 0xb4, 0x2c, 0x49, 0x4c, 0xd8, 0x72, 0x90, 0x8e, 0x83, 0xbc, 0x22, 0x89, 0xc1,
	0x2e, 0x1c, 0x49, 0xd8, 0xc1, 0x2c, 0xe1, 0xc6, 0x32, 0x5d, 0x75, 0x80, 0xd9, 0x59, 0xc6, 0x8c,
	0x45, 0x93, 0xba, 0x35, 0x67, 0xa9, 0x3b, 0xba, 0x1d, 0xaf, 0x9c, 0x41, 0x5c, 0xab, 0x52, 0x23,
	0x47, 0x02, 0x76, 0x7d, 0x7a, 0x26, 0x55, 0xd2, 0x30, 0xf4, 0x12, 0x2e, 0x1f, 0x48, 0x63, 0x89,
	0xa4, 0xec, 0x98, 0xb3, 0xf3, 0x52, 0xee, 0x8e, 0x93, 0x5b, 0x4d, 0x5d, 0x86, 0xe3, 0x0a, 0x39,
	0x4a, 0x61, 0xef, 0x39, 0xd3, 0xff, 0xb3, 0xc1, 0x33, 0xe8, 0xfb, 0x15, 0xcb, 0x16, 0x27, 0x2b,
	0x5b, 0xbc, 0xeb, 0x04, 0x7d, 0xe4, 0x35, 0x4d, 0xfe, 0x6c, 0xc0, 0x5e, 0x4d, 0x29, 0x93, 0xcf,
	0x94, 0x10, 0x44, 0x4e, 0xff, 0x4d, 0x97, 0x68, 0x0c, 0xed, 0x23, 0x95, 0x69, 0xca, 0xdc, 0x3a,
	0xfe, 0xf6, 0xee, 0x33, 0x71, 0x44, 0x35, 0x4f, 0x6d, 0x41, 0xc0, 0x25, 0x11, 0x71, 0xb8, 0xb9,
	0x40, 0x1c, 0xc8, 0x34, 0xb3, 0x87, 0x44, 0x13, 0xc1, 0x2c, 0xd3, 0x26, 0x6c, 0xf6, 0x9b, 0x83,
	0xee, 0xe8, 0xfe, 0xda, 0xaa, 0x55, 0x0e, 0xf6, 0x57, 0x43, 0x11, 0x74, 0x70, 0x26, 0xc7, 0xe6,
	0xb5, 0x61, 0xda, 0x1d, 0x42, 0x67, 0xbf, 0xf5, 0xe5, 0x7b, 0x18, 0xe0, 0x45, 0x18, 0xdd, 0x83,
	0x2b, 0xee, 0xc7, 0x21, 0x31, 0xe6, 0x5c, 0xe9, 0x69, 0x78, 0x69, 0x09, 0x57, 0x4d, 0x45, 0x3f,
	0x02, 0xe8, 0xfb, 0x07, 0x3e, 0xff, 0x93, 0xff, 0xea, 0xc4, 0xeb, 0x3b, 0xf3, 0x27, 0x73, 0xf7,
	0xef, 0xcc, 0xe8, 0x5b, 0x13, 0xae, 0x56, 0x69, 0xe3, 0xdc, 0x0d, 0xfa, 0x1c, 0xc0, 0xf5, 0xd5,
	0x57, 0x86, 0x1e, 0x79, 0x8c, 0xaf, 0x7d, 0x7e, 0xf4, 0x1e, 0x5f, 0x90, 0x55, 0x4c, 0x2f, 0xda,
	0x42, 0x5f, 0x03, 0x08, 0x7d, 0xc7, 0x80, 0x9e, 0x78, 0xaa, 0x6e, 0x38, 0xf6, 0xde, 0xd3, 0x0b,
	0xf3, 0xe6, 0x7e, 0x3e, 0x01, 0x2c, 0x26, 0xeb, 0x35, 0xb0, 0xe1, 0x0e, 0xbd, 0x06, 0x36, 0xad,
	0x53, 0xb4, 0xb5, 0xff, 0xe0, 0x4d, 0x9c, 0x70, 0x3b, 0xcb, 0x4e, 0x73, 0xd2, 0x50, 0x70, 0xaa,
	0x95, 0x51, 0x6f, 0xed, 0x50, 0x28, 0x3a, 0xd4, 0x29, 0x1d, 0xce, 0x8b, 0x0e, 0xcb, 0xa2, 0xa7,
	0x6d, 0xf7, 0x76, 0x79, 0xf8, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xab, 0xd8, 0x30, 0x97, 0xd3, 0x06,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VirtualMachineAgentClient is the client API for VirtualMachineAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VirtualMachineAgentClient interface {
	RegisterVirtualMachine(ctx context.Context, in *RegisterVirtualMachineRequest, opts ...grpc.CallOption) (*RegisterVirtualMachineResponse, error)
	DeregisterVirtualMachine(ctx context.Context, in *DeregisterVirtualMachineRequest, opts ...grpc.CallOption) (*DeregisterVirtualMachineResponse, error)
	RunCommand(ctx context.Context, in *VirtualMachineRunCommandRequest, opts ...grpc.CallOption) (*VirtualMachineRunCommandResponse, error)
}

type virtualMachineAgentClient struct {
	cc *grpc.ClientConn
}

func NewVirtualMachineAgentClient(cc *grpc.ClientConn) VirtualMachineAgentClient {
	return &virtualMachineAgentClient{cc}
}

func (c *virtualMachineAgentClient) RegisterVirtualMachine(ctx context.Context, in *RegisterVirtualMachineRequest, opts ...grpc.CallOption) (*RegisterVirtualMachineResponse, error) {
	out := new(RegisterVirtualMachineResponse)
	err := c.cc.Invoke(ctx, "/moc.hostagent.compute.VirtualMachineAgent/RegisterVirtualMachine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineAgentClient) DeregisterVirtualMachine(ctx context.Context, in *DeregisterVirtualMachineRequest, opts ...grpc.CallOption) (*DeregisterVirtualMachineResponse, error) {
	out := new(DeregisterVirtualMachineResponse)
	err := c.cc.Invoke(ctx, "/moc.hostagent.compute.VirtualMachineAgent/DeregisterVirtualMachine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineAgentClient) RunCommand(ctx context.Context, in *VirtualMachineRunCommandRequest, opts ...grpc.CallOption) (*VirtualMachineRunCommandResponse, error) {
	out := new(VirtualMachineRunCommandResponse)
	err := c.cc.Invoke(ctx, "/moc.hostagent.compute.VirtualMachineAgent/RunCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VirtualMachineAgentServer is the server API for VirtualMachineAgent service.
type VirtualMachineAgentServer interface {
	RegisterVirtualMachine(context.Context, *RegisterVirtualMachineRequest) (*RegisterVirtualMachineResponse, error)
	DeregisterVirtualMachine(context.Context, *DeregisterVirtualMachineRequest) (*DeregisterVirtualMachineResponse, error)
	RunCommand(context.Context, *VirtualMachineRunCommandRequest) (*VirtualMachineRunCommandResponse, error)
}

// UnimplementedVirtualMachineAgentServer can be embedded to have forward compatible implementations.
type UnimplementedVirtualMachineAgentServer struct {
}

func (*UnimplementedVirtualMachineAgentServer) RegisterVirtualMachine(ctx context.Context, req *RegisterVirtualMachineRequest) (*RegisterVirtualMachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterVirtualMachine not implemented")
}
func (*UnimplementedVirtualMachineAgentServer) DeregisterVirtualMachine(ctx context.Context, req *DeregisterVirtualMachineRequest) (*DeregisterVirtualMachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeregisterVirtualMachine not implemented")
}
func (*UnimplementedVirtualMachineAgentServer) RunCommand(ctx context.Context, req *VirtualMachineRunCommandRequest) (*VirtualMachineRunCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunCommand not implemented")
}

func RegisterVirtualMachineAgentServer(s *grpc.Server, srv VirtualMachineAgentServer) {
	s.RegisterService(&_VirtualMachineAgent_serviceDesc, srv)
}

func _VirtualMachineAgent_RegisterVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterVirtualMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineAgentServer).RegisterVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.hostagent.compute.VirtualMachineAgent/RegisterVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineAgentServer).RegisterVirtualMachine(ctx, req.(*RegisterVirtualMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineAgent_DeregisterVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterVirtualMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineAgentServer).DeregisterVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.hostagent.compute.VirtualMachineAgent/DeregisterVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineAgentServer).DeregisterVirtualMachine(ctx, req.(*DeregisterVirtualMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineAgent_RunCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtualMachineRunCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineAgentServer).RunCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.hostagent.compute.VirtualMachineAgent/RunCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineAgentServer).RunCommand(ctx, req.(*VirtualMachineRunCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VirtualMachineAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moc.hostagent.compute.VirtualMachineAgent",
	HandlerType: (*VirtualMachineAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterVirtualMachine",
			Handler:    _VirtualMachineAgent_RegisterVirtualMachine_Handler,
		},
		{
			MethodName: "DeregisterVirtualMachine",
			Handler:    _VirtualMachineAgent_DeregisterVirtualMachine_Handler,
		},
		{
			MethodName: "RunCommand",
			Handler:    _VirtualMachineAgent_RunCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moc_hostagent_virtualmachine.proto",
}
