// Code generated by protoc-gen-go. DO NOT EDIT.
// source: exec/moc_hostagent_exec.proto

package admin

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	common "github.com/microsoft/moc/rpc/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExecRequest struct {
	Execs                []*Exec          `protobuf:"bytes,1,rep,name=Execs,proto3" json:"Execs,omitempty"`
	OperationType        common.Operation `protobuf:"varint,2,opt,name=OperationType,proto3,enum=moc.Operation" json:"OperationType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ExecRequest) Reset()         { *m = ExecRequest{} }
func (m *ExecRequest) String() string { return proto.CompactTextString(m) }
func (*ExecRequest) ProtoMessage()    {}
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ced3511aee2255fb, []int{0}
}

func (m *ExecRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecRequest.Unmarshal(m, b)
}
func (m *ExecRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecRequest.Marshal(b, m, deterministic)
}
func (m *ExecRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecRequest.Merge(m, src)
}
func (m *ExecRequest) XXX_Size() int {
	return xxx_messageInfo_ExecRequest.Size(m)
}
func (m *ExecRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecRequest proto.InternalMessageInfo

func (m *ExecRequest) GetExecs() []*Exec {
	if m != nil {
		return m.Execs
	}
	return nil
}

func (m *ExecRequest) GetOperationType() common.Operation {
	if m != nil {
		return m.OperationType
	}
	return common.Operation_GET
}

type ExecResponse struct {
	Execs                []*Exec             `protobuf:"bytes,1,rep,name=Execs,proto3" json:"Execs,omitempty"`
	Result               *wrappers.BoolValue `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
	Error                string              `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ExecResponse) Reset()         { *m = ExecResponse{} }
func (m *ExecResponse) String() string { return proto.CompactTextString(m) }
func (*ExecResponse) ProtoMessage()    {}
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ced3511aee2255fb, []int{1}
}

func (m *ExecResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecResponse.Unmarshal(m, b)
}
func (m *ExecResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecResponse.Marshal(b, m, deterministic)
}
func (m *ExecResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecResponse.Merge(m, src)
}
func (m *ExecResponse) XXX_Size() int {
	return xxx_messageInfo_ExecResponse.Size(m)
}
func (m *ExecResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecResponse proto.InternalMessageInfo

func (m *ExecResponse) GetExecs() []*Exec {
	if m != nil {
		return m.Execs
	}
	return nil
}

func (m *ExecResponse) GetResult() *wrappers.BoolValue {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ExecResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Exec struct {
	Command              string         `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Output               string         `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Status               *common.Status `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Exec) Reset()         { *m = Exec{} }
func (m *Exec) String() string { return proto.CompactTextString(m) }
func (*Exec) ProtoMessage()    {}
func (*Exec) Descriptor() ([]byte, []int) {
	return fileDescriptor_ced3511aee2255fb, []int{2}
}

func (m *Exec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Exec.Unmarshal(m, b)
}
func (m *Exec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Exec.Marshal(b, m, deterministic)
}
func (m *Exec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exec.Merge(m, src)
}
func (m *Exec) XXX_Size() int {
	return xxx_messageInfo_Exec.Size(m)
}
func (m *Exec) XXX_DiscardUnknown() {
	xxx_messageInfo_Exec.DiscardUnknown(m)
}

var xxx_messageInfo_Exec proto.InternalMessageInfo

func (m *Exec) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Exec) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func (m *Exec) GetStatus() *common.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*ExecRequest)(nil), "moc.hostagent.admin.ExecRequest")
	proto.RegisterType((*ExecResponse)(nil), "moc.hostagent.admin.ExecResponse")
	proto.RegisterType((*Exec)(nil), "moc.hostagent.admin.Exec")
}

func init() { proto.RegisterFile("exec/moc_hostagent_exec.proto", fileDescriptor_ced3511aee2255fb) }

var fileDescriptor_ced3511aee2255fb = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcf, 0x4a, 0xe3, 0x40,
	0x1c, 0xde, 0x6c, 0xb7, 0x59, 0x3a, 0xd9, 0xed, 0x61, 0x76, 0xd9, 0xcd, 0x06, 0x56, 0x62, 0xbc,
	0xf4, 0x20, 0x33, 0x10, 0x7d, 0x01, 0x0b, 0x3d, 0x78, 0x2a, 0x44, 0xf1, 0x20, 0x4a, 0x49, 0xa7,
	0xd3, 0x34, 0x98, 0xe4, 0x37, 0xce, 0x1f, 0xad, 0x8f, 0xe0, 0x5b, 0xcb, 0xcc, 0xa4, 0x05, 0x41,
	0x05, 0x4f, 0xe1, 0x9b, 0xef, 0x5f, 0xe6, 0x4b, 0xd0, 0x7f, 0xbe, 0xe5, 0x8c, 0xb6, 0xc0, 0x16,
	0x1b, 0x50, 0xba, 0xac, 0x78, 0xa7, 0x17, 0xf6, 0x88, 0x08, 0x09, 0x1a, 0xf0, 0xaf, 0x16, 0x18,
	0xd9, 0x33, 0xa4, 0x5c, 0xb5, 0x75, 0x97, 0x1c, 0x54, 0x00, 0x55, 0xc3, 0xa9, 0x93, 0x2c, 0xcd,
	0x9a, 0x3e, 0xca, 0x52, 0x08, 0x2e, 0x95, 0x37, 0x25, 0x7f, 0x6d, 0x1c, 0x83, 0xb6, 0x85, 0xae,
	0x7f, 0x78, 0x22, 0xd3, 0x28, 0x9a, 0x6d, 0x39, 0x2b, 0xf8, 0xbd, 0xe1, 0x4a, 0x63, 0x8a, 0x86,
	0x16, 0xaa, 0x38, 0x48, 0x07, 0x93, 0x28, 0xff, 0x47, 0xde, 0x28, 0x23, 0xce, 0xe0, 0x75, 0xf8,
	0x14, 0xfd, 0x9c, 0x0b, 0x2e, 0x4b, 0x5d, 0x43, 0x77, 0xf9, 0x24, 0x78, 0xfc, 0x35, 0x0d, 0x26,
	0xe3, 0x7c, 0xec, 0x8c, 0x7b, 0xa6, 0x78, 0x2d, 0xca, 0x9e, 0x03, 0xf4, 0xc3, 0xd7, 0x2a, 0x01,
	0x9d, 0xe2, 0x9f, 0xef, 0xcd, 0x51, 0x58, 0x70, 0x65, 0x1a, 0xed, 0x0a, 0xa3, 0x3c, 0x21, 0x7e,
	0x01, 0xb2, 0x5b, 0x80, 0x4c, 0x01, 0x9a, 0xab, 0xb2, 0x31, 0xbc, 0xe8, 0x95, 0xf8, 0x37, 0x1a,
	0xce, 0xa4, 0x04, 0x19, 0x0f, 0xd2, 0x60, 0x32, 0x2a, 0x3c, 0xc8, 0x6e, 0xd1, 0x37, 0x1b, 0x89,
	0x63, 0xf4, 0xdd, 0x2e, 0x53, 0x76, 0xab, 0x38, 0x70, 0xfc, 0x0e, 0xe2, 0x3f, 0x28, 0x04, 0xa3,
	0x85, 0xf1, 0x5d, 0xa3, 0xa2, 0x47, 0xf8, 0x08, 0x85, 0x4a, 0x97, 0xda, 0x28, 0x17, 0x18, 0xe5,
	0x91, 0x7b, 0xeb, 0x0b, 0x77, 0x54, 0xf4, 0x54, 0x7e, 0x83, 0x46, 0x36, 0xfe, 0xcc, 0xde, 0x03,
	0xcf, 0x51, 0x78, 0xde, 0x3d, 0xc0, 0x1d, 0xc7, 0xe9, 0xfb, 0x37, 0xf4, 0x9f, 0x22, 0x39, 0xfc,
	0x40, 0xe1, 0x57, 0xcb, 0xbe, 0x4c, 0xc9, 0xf5, 0x71, 0x55, 0xeb, 0x8d, 0x59, 0x12, 0x06, 0x2d,
	0x6d, 0x6b, 0x26, 0x41, 0xc1, 0x5a, 0xdb, 0xbf, 0x87, 0x4a, 0xc1, 0xe8, 0xde, 0x4e, 0x9d, 0x7d,
	0x19, 0xba, 0x79, 0x4e, 0x5e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x7d, 0x75, 0xda, 0x64, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExecAgentClient is the client API for ExecAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExecAgentClient interface {
	Invoke(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
}

type execAgentClient struct {
	cc *grpc.ClientConn
}

func NewExecAgentClient(cc *grpc.ClientConn) ExecAgentClient {
	return &execAgentClient{cc}
}

func (c *execAgentClient) Invoke(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, "/moc.hostagent.admin.ExecAgent/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecAgentServer is the server API for ExecAgent service.
type ExecAgentServer interface {
	Invoke(context.Context, *ExecRequest) (*ExecResponse, error)
}

// UnimplementedExecAgentServer can be embedded to have forward compatible implementations.
type UnimplementedExecAgentServer struct {
}

func (*UnimplementedExecAgentServer) Invoke(ctx context.Context, req *ExecRequest) (*ExecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}

func RegisterExecAgentServer(s *grpc.Server, srv ExecAgentServer) {
	s.RegisterService(&_ExecAgent_serviceDesc, srv)
}

func _ExecAgent_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecAgentServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.hostagent.admin.ExecAgent/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecAgentServer).Invoke(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExecAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moc.hostagent.admin.ExecAgent",
	HandlerType: (*ExecAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _ExecAgent_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exec/moc_hostagent_exec.proto",
}
